name: Auto Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行一次

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with upstream
        run: |
          git fetch upstream
          git merge upstream/main
          git push
